name: JEss
version: '${project.version}'
main: jfbdev.jess.JEss
api-version: '1.16'
authors: [jFrostyBoy]
description: Manager features at your server

commands:
  jessreload:
    usage: /<command>
  heal:
    usage: /<command>
  feed:
    usage: /<command>
  fly:
    usage: /<command>
  flyspeed:
    usage: /<command>
